"""LLM provider client with Gemini API and offline deterministic fallback."""

import json
import os
import re
from typing import Dict, Any, List, Optional
from src.generator.prompts import SYSTEM_GROUNDED_REPLY_PROMPT


class LLMClient:
    """Client for generating grounded replies using Gemini API or offline fallback."""

    def __init__(
        self,
        provider: str = "gemini",
        model_name: str = "gemini-2.5-flash",
        temperature: float = 0.0,
        api_key: Optional[str] = None
    ):
        self.provider = provider
        self.model_name = model_name
        self.temperature = temperature
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.gemini_model = None

        if self.provider == "gemini" and self.api_key:
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.api_key)
                self.gemini_model = genai.GenerativeModel(
                    model_name=self.model_name,
                    system_instruction=SYSTEM_GROUNDED_REPLY_PROMPT
                )
            except Exception:
                self.gemini_model = None

    def generate(self, user_prompt: str, evidence_blocks: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generates a grounded JSON response."""
        if self.gemini_model:
            try:
                resp = self.gemini_model.generate_content(
                    user_prompt,
                    generation_config={
                        "temperature": self.temperature,
                        "response_mime_type": "application/json"
                    }
                )
                txt = resp.text.strip()
                data = json.loads(txt)
                return {
                    "draft_text": data.get("draft_text", ""),
                    "cited_evidence_ids": data.get("cited_evidence_ids", []),
                    "grounding_rationale": data.get("grounding_rationale", "Generated by Gemini API")
                }
            except Exception as e:
                pass

        # Deterministic Offline / Fallback Generator
        # Synthesizes the grounded reply directly from top evidence resolution
        if not evidence_blocks:
            return {
                "draft_text": "We'd like to look into this. Please send us a DM with your device model and iOS version.",
                "cited_evidence_ids": [],
                "grounding_rationale": "No evidence retrieved; suggested DM escalation"
            }

        top_ev = evidence_blocks[0]
        ev_id = top_ev["id"]
        res_text = top_ev["resolution"]

        # Adapt resolution text into a grounded draft reply
        draft_text = f"We can help with that. {res_text}"
        if len(draft_text) > 280:
            draft_text = res_text[:275] + "..."

        return {
            "draft_text": draft_text,
            "cited_evidence_ids": [ev_id],
            "grounding_rationale": f"Synthesized from historical resolution of #{ev_id}"
        }
